### ISSUE TITLE
Email system for the timeslice project

### ISSUE THREAD

**Issue by C-Carr22** [stfc-aeg/for-review#2]
Added an email system to send timeslice video renders based on access code inputs. Also cleared out unnecessary odin-workshop items and commented python code.

https://github.com/stfc-aeg/odin-timeslice/tree/email-system

Acceptance Criteria:

- [ ] when access codes [ AP95VE4, DBU982W, 194V6S3 ] and valid email address are entered, an email with the mp4 files attatched sends.
- [ ] email should contain a list of the entered codes
- [ ] unnecessary workshop code is removed
- [ ] code is sufficiently commented
- [ ] code list should clear when clear button is clicked and when page is reloaded

**Comment by ANeaves** [comment]
Couple Notes from when we viewed it Friday:
- Change the names of the attachments. Receiving an attachment in an email with a random string of letters and numbers might cause people to worry about viruses.
- The page needs to clear the boxes for access codes and the user email when done, so that the next user doesn't see those details, not sure if it was doing that when you demoed
- there's no Pull Request currently for this branch? Might be worth setting one up to make the review process easier

**Comment by C-Carr22** [comment]
On the change in attachment names, I've put this together which does the job correctly but I'm unsure if I've done this in the best/most efficient way. Any thoughts?

![Video_Names](https://user-images.githubusercontent.com/44807020/64533519-920df500-d30b-11e9-8e94-d7fd2eb528d2.PNG)

**Comment by C-Carr22** [comment]
Suggested changes have been made and are covered in this pull request:
https://github.com/stfc-aeg/odin-timeslice/pull/4

**Comment by C-Carr22** [comment]
All done :)
