### ISSUE TITLE
Update to the timeslice user interface

### ISSUE THREAD

**Issue by C-Carr22** [stfc-aeg/for-review#8]
Update to the timeslice user interface to match designed workflow and aesthetics

https://github.com/stfc-aeg/odin-timeslice/pull/5

**Acceptance Criteria**
- [x] UI is user friendly and easy to use
- [x] UI looks good
- [x] movement between 'pages' makes sense and is smooth
- [x] users cannot get to the send email stage without having both an email address and access codes entered ( AP95VE4, DBU982W, ASDFGHJ, 194V6S3 )

**Code Review**
 - [x] Is the code of an acceptable quality?
 - [x] Do the changes function as described and is it robust?
 - [x] Have the changes been documented (e.g. in commits, PR merges, release notes or documentation)?

**Comment by timcnicholls** [comment]
Made some initial suggestions/feedback to @C-Carr22 after a demo 
- [x] change workflow order (codes then email)
- [x] add some branding (logo + navbar with single "Help" popup item), 
- [x] use bootstrap buttons rather than pure CSS
- [x] change "Send test email" button text
- [x] change page title from "ODIN Timeslice" to something meaningful to non-expert user

These are minor tweaks as it already looks good. Suggest you solicit another 'disinterested' reviewer once those changes are made!

**Comment by C-Carr22** [comment]
Changes made and committed, ready for review in the linked pull request.

**Comment by C-Carr22** [comment]
New commit regarding moving email content into a config file, ready for review

**Comment by timcnicholls** [comment]
Can confirm all suggested feedback above has been implemented and the UI looks great. 

Suggest that @ANeaves now reviews this as a final step for feedback as a non-expert user.
